name = "flareact-template"
type = "webpack"
account_id = "bf20139f13fc9c14fb7fb2cb7bf5f7c6"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "node_modules/flareact/webpack"

[site]
bucket = "out"
entry-point = "./"
